package learning.types

/*******************************************************************
*******************************************************************
Desugaring Enumerations
-------------------------------------------------------------------
Every `enum` is syntactic sugar. The compiler expands it into:

  1. A `sealed abstract class` extending `scala.reflect.Enum`
     (which requires each case to implement `def ordinal: Int`)
  2. A companion `object` containing the expanded cases

Enum cases fall into three categories
(see https://docs.scala-lang.org/scala3/reference/enums/desugarEnums.html):

  SIMPLE CASE    — name only, no params, no extends clause
                   e.g.  case North
                   desugars to: val North = $new(n, "North")
                   ($new is a private factory that creates the singleton)

  VALUE CASE     — has an explicit `extends` clause (and/or body)
                   but no parameter section
                   e.g.  case Red extends ADTColor(0xFF0000)
                   desugars to: val Red = new ADTColor(...) { def ordinal = n }

  CLASS CASE     — has a parameter section (may also have extends)
                   e.g.  case Mix(mix: Int) extends ADTColor(mix)
                   desugars to: final case class Mix(...) extends ADTColor(mix) {
                                    def ordinal = n }

Singleton cases (simple + value) are expanded to `val` definitions.
Class cases are expanded to `final case class` definitions.

Note: the Scala 3 book (https://docs.scala-lang.org/scala3/book/types-adts-gadts.html)
shows a simplified desugaring using `case object` for readability. The actual
compiler output uses anonymous `val`s for singleton cases. Both represent the
same concept — a named singleton with a fixed ordinal.

Using `enum` is preferred over manual encoding because the compiler
also generates `values`, `valueOf`, and `fromOrdinal` utilities for free.
*******************************************************************
*******************************************************************/

// --- Rule 1: enum expands to a sealed abstract class + companion object ---
sealed abstract class ADTColor2(val rgb: Int) extends scala.reflect.Enum

object ADTColor2:
    // VALUE CASES — simplified form as shown in the Scala 3 book.
    // The book uses `case object` for readability. The actual compiler output
    // per the spec is: val Red = new ADTColor2(0xFF0000) { def ordinal = 0 }
    // Both represent the same idea: a named singleton with a fixed ordinal.
    case object Red   extends ADTColor2(0xFF0000) { override def ordinal = 0 }
    case object Green extends ADTColor2(0x00FF00) { override def ordinal = 1 }
    case object Blue  extends ADTColor2(0x0000FF) { override def ordinal = 2 }

    // CLASS CASE — has a parameter section, so it's not a singleton.
    // Actual compiler output: final case class Mix(mix: Int) extends ADTColor2(mix) {
    //                             def ordinal = 3 }
    // Each call to Mix(...) creates a new instance; ordinal is always 3.
    final case class Mix(mix: Int) extends ADTColor2(mix) { override def ordinal = 3 }

    // `fromOrdinal` is generated automatically by the compiler for real enums.
    // Shown here manually to illustrate what it does: map ordinal → case.
    // Note: Mix is excluded because it is a class case (not a singleton),
    // so there is no single instance to return for ordinal 3.
    def fromOrdinal(ordinal: Int): ADTColor2 = ordinal match
        case 0 => Red
        case 1 => Green
        case 2 => Blue
        case _ => throw new NoSuchElementException(ordinal.toString)

// --- SIMPLE CASE example (the third category) ---
// A simple case has no params and no extends clause; only valid on non-generic enums.
// The compiler generates: val North = $new(0, "North")
// $new is a private factory that builds a singleton implementing ordinal + toString.
enum Direction:
    case North, South, East, West   // all four are simple cases

def desugarExample() =
    // value cases — ordinal reflects declaration order
    println(ADTColor2.Red.ordinal)    // 0
    println(ADTColor2.Green.ordinal)  // 1
    println(ADTColor2.Blue.ordinal)   // 2

    // class case — a fresh instance each time, ordinal is always 3
    val m1 = ADTColor2.Mix(0xFF0000)
    val m2 = ADTColor2.Mix(0x00FF00)
    println(m1.ordinal)               // 3
    println(m2.ordinal)               // 3
    println(m1 == m2)                 // false — different instances, different rgb

    // fromOrdinal — manual version shown above
    println(ADTColor2.fromOrdinal(0)) // Red

    // simple cases — valueOf and values are generated by the compiler for free
    println(Direction.North)                          // North
    println(Direction.valueOf("East"))                // East
    println(Direction.values.mkString(", "))          // North, South, East, West
